### PR TITLE
Fixes the Typescript support

### PR DESCRIPTION
**Pull request by ianko**
Added the `declare module` and changed the `package.json` for the latest Typescript support.

### CODE REVIEW

**Comment by icholy** [comment]
@ianko I'd prefer if it was a UMD module so it still works as a global import. Something like this:

``` typescript
export as namespace durationJs;
```

**Comment by CameronDiver** [comment]
@icholy do you know when a version will be released which has typescript support? (Either before or after this PR)

**Comment by icholy** [comment]
@CameronDiver the problem is that, if I change to use es6 modules, it will break my usage (I’m still using global in a legacy app). Not sure how to move forward, maybe a separate branch?

**Comment by CameronDiver** [comment]
It also seems that we can keep the support the same by doing
```Typescript
export = Duration;
```
in `duration.d.ts` and this keeps things working nicely, with Typescript imports working like:
```typescript
import Duration = require('duration-js')
```

**Comment by augustobreno** [comment]
Hi all... this merge will be done some day?

**Comment by icholy** [comment]
This PR is no longer relevant because the code is written directly in typescript.

**Pull request closed without merging**
